### ISSUE TITLE
Support the environment variable syntax when setting secrets

### ISSUE THREAD

**Issue by kawazoe** [aspnet/DotNetTools#333]
Trying to use the following command will generate an unexpected json output:

Command: `dotnet user-secrets set foo:bar test`
Expected json: ` { "foo": { "bar": "test" } }`
Actual json: `{ "foo:bar": "test" }`

Since the user secret loader uses the json loader behind the scenes, and that loader does not try to parse keys the same way as the environment variable loader does, the current secret file will not work.

As a side note, I consider the actual json to be unexpected because listing the expected json (using the SecretManager.Tools) outputs `foo:bar = test`.

Workaround: open the secret.json file in a text editor and set the content manually.

**Comment by natemcmaster** [comment]
Can you clarify what you mean by environment variable syntax? Do you mean you want double underscores? i.e. `dotnet user-secrets set foo__bar test`

> the current secret file will not work.

What are you seeing that doesn't work? The configuration values discovered by the JSON loader are the same for `{ "foo": { "bar": "test" } }` and `{ "foo:bar": "test" }`. 

FYI this flattening behavior is intentional. In fact, we had bugs when we attemped to be smart about nesting. See https://github.com/aspnet/UserSecrets/pull/94, https://github.com/aspnet/UserSecrets/issues/79, and https://github.com/aspnet/UserSecrets/issues/22.

**Comment by muratg** [comment]
This is by:design, as @natemcmaster has explained above.
