### ISSUE TITLE
Consider redesigning the interface of developer certificates

### ISSUE THREAD

**Issue by javiercn** [aspnet/DotNetTools#357]
Right now the tool offers a single command that ensure the target system is in the right state after running
```dotnet developercertificates https```

Consider moving towards a CRUD API to manage the developer certificates on the machine.
```
dotnet devcerts list
dotnet devcerts create
dotnet devcerts remove
```

**Comment by natemcmaster** [comment]
cc @mkArtakMSFT 

I think this is worth considering as it gives you the most flexibility in the future. By using flags instead of subcommands, it can be difficult for users to figure out which combinations of flags are valid. Subcommands help you scope flags.

For example, this doesn't work: `dotnet dev-certs --password --check`, but `dotnet dev-certs --help` doesn't make that obvious. This problem grows as you expand to more features.

Subcommands would allow you to only allow `--password` and others to the command where it makes sense.

**Comment by muratg** [comment]
Any plans to do this soon (i.e in 2.1.0 timeline) @javiercn?

**Comment by javiercn** [comment]
We are waiting for customer feedback. @danroth27 is responsible for this.

**Comment by KathleenDollard** [comment]
I like @javiercn suggestion for syntax here. Overall, tending to subcommands and encouraging external authors that direction makes sense to me.

**Comment by danroth27** [comment]
The design of the tool is deliberately very targeted and task centric. You run `dotnet dev-certs https --trust` once to setup/trust your certificate and then never think about it again (In the rare case that the SDK/VS hasn't already done it for you). This isn't a tool we envision users interacting with regularly with many different verbs.  I think the current user interface is suffcient.
