### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by johnkors** [aspnet/DotNetTools#390]
```
λ dotnet --version
2.1.300-preview2-008017
```

Given a project
```
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp2.1</TargetFramework>
    <RuntimeFrameworkVersion>2.1.0-preview1-26115-03</RuntimeFrameworkVersion>
    <NETStandardImplicitPackageVersion>2.0.1</NETStandardImplicitPackageVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.All" Version="2.1.0-preview1-28124" />
  </ItemGroup>
</Project>
```

Trying to install like the doc say, fail cause of it's not released yet I guess:

```
λ dotnet install tool --global dotnet-watch
Install failed. Failed to download package:
NuGet returned:

Failed to restore package.
error NU1103: Unable to find a stable package dotnet-watch with version
error NU1103:   - Found 144 version(s) in myget-aspnetcore-dev [ Nearest version: 2.1.0-preview1-27934 ]
```

Ok, so knowing that - we try specifying the version in question explicitly:
```
λ dotnet install tool --global dotnet-watch --version 2.1.0-preview1-27934
Install failed. Failed to download package:
NuGet returned:

Failed to restore package.
 error NU1202: Package dotnet-watch 2.1.0-preview1-27934 is not compatible with netcoreapp2.1 (.NETCoreApp,Version=v2.1) / win10-x64. Package dotnet-watch 2.1.0-preview1-27934 supports: netcoreapp2.1 (.NETCoreApp,Version=v2.1) / any
 
```

What does this mean? What am I missing?

**Comment by natemcmaster** [comment]
dotnet-watch 2.1.0-preview1-27934 came before this change: https://github.com/aspnet/DotNetTools/pull/385. The CLI make breaking changes in requirements for dotnet-install-tool. Try using dotnet-watch 2.1.0-preview2-30015

**Comment by johnkors** [comment]
Followup: Was able to install `2.1.0-preview2-30015`, but:
```
λ dotnet watch
It was not possible to find any compatible framework version
The specified framework 'Microsoft.NETCore.App', version '2.1.0-preview2-26130-04' was not found.
  - Check application dependencies and target a framework version installed at:
      C:\Program Files\dotnet\
  - The .NET framework can be installed from:
      https://aka.ms/dotnet-download-runtime
  - The .NET framework and SDK can be installed from:
      http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
  - The following versions are installed:
      1.0.0 at [C:\Program Files\dotnet\shared]
      1.0.1 at [C:\Program Files\dotnet\shared]
      1.0.3 at [C:\Program Files\dotnet\shared]
      1.0.4 at [C:\Program Files\dotnet\shared]
      1.0.5 at [C:\Program Files\dotnet\shared]
      1.1.0 at [C:\Program Files\dotnet\shared]
      1.1.1 at [C:\Program Files\dotnet\shared]
      1.1.2 at [C:\Program Files\dotnet\shared]
      2.0.0 at [C:\Program Files\dotnet\shared]
      2.0.0-preview2-25407-01 at [C:\Program Files\dotnet\shared]
      2.0.3 at [C:\Program Files\dotnet\shared]
      2.0.5 at [C:\Program Files\dotnet\shared]
      2.1.0-preview1-26116-04 at [C:\Program Files\dotnet\shared]
```

**Comment by wli3** [comment]
@johnkors preview runtime version won't move forward.(if you have, say v9.6 on your machine, if the tool ask for v9.3, tool will use 9.6 instead. But this is not the case for previews) You need to install required preview runtime version.

**Comment by johnkors** [comment]
Ok, where can I find it? It's nearly impossible to find the installer for a specific runtime version, and finding the previews are even harder :/

**Comment by natemcmaster** [comment]
Daily builds of the ASP.NET Core runtime installers are here: https://github.com/aspnet/Universe#daily-builds
.NET Core runtime: https://github.com/dotnet/core-setup#daily-builds

**Comment by natemcmaster** [comment]
Unfortunately, this experience isn't something we can make easier at the moment. There is no way for a global tool package to ensure installation of the shared .NET Core runtime it depends on.

By the time we release a stable version of dotnet-watch, I hope this will be less of an issue. dotnet-watch will depend on stable, released versions of .NET Core 2.1. Our nightly builds are rapidly changing and download links are not always easy to find, but stable RTM builds should be posted to https://aka.ms/dotnet-download-runtime.

Closing for now as there isn't any action we can take on our tools packages. But feel free to discuss if installing the nightly build of the .NET Core 2.1 runtime doesn't fix this issue.

**Comment by simeyla** [comment]
@natemcmaster Unfortunately, this experience isn't something we can make easier at the moment.

**Yes there is! - An idiot proof step by step guide that's referenced from many places.**

I've managed to figure it out eventually but figuring out all the pieces was a chore - and some of the docs are just way to technical and start talking about muxers and the like.  Do I need to know about muxers? I still don't know.

What confused the **heck** out of me when I thought I was on the track - is the distinction between ASP.NET Core and .NET Core runtime. I didn't realize they were separate installs, and I'm still confused to be honest if I ever need to install both. 

For instance I managed to figure out I needed to use the myget feed (in VS2017) which tells me for all the ASP.NET packages that they're `2.1.0-preview2-30285`.

So now I need to find the runtime because the error says it's missing - and I'm[ looking at a page](https://github.com/dotnet/core-setup#daily-builds) which has `2.1.0-preview2-26310-01` in the 'master' branch. I don't really know why they're different so I install it anywhere and it doesn't work. And it says 2.1.0-preview2` which sounds **SOOO* close to what I need!

Then fortunately I found your comment above noting the distinction and then was able to get the [ASP.NET build I needed](https://github.com/aspnet/Universe#daily-builds). 

And this is called `Universe` which is a term I've never even heard before! 

And then [pages like this](https://github.com/dotnet/core/blob/master/daily-builds.md) aren't updated to say Preview 2 so it just adds to the confusion.

A guide on how to use the bits must exist somewhere - but if it does I never found it. 

(And all this because of a missing ORDER BY in EF Core Sql). 

Happy now :-)

**Comment by natemcmaster** [comment]
@simeyla the context of this issue was about using nightly builds of dotnet-watch, which is just one part of the entire .NET Core world. But I hear your frustration in trying to use nightly builds of Entity Framework Core. If you need more guidance on how all these pieces fit together, I recommend using our "Home" repo: https://github.com/aspnet/Home. It serves as a landing page for all projects in https://github.com/aspnet.
